---

repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7

  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.24.2
    hooks:
      - id: yamllint
        args: ['-d relaxed']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-json
      - id: check-merge-conflict

  - repo: https://github.com/PyCQA/isort
    rev: 5.4.2
    hooks:
      - id: isort
